#!/usr/bin/env python3
import sys

from tabulate import tabulate

sys.path.append(".")

from lifeguard.settings import SETTINGS_MANAGER

if __name__ == "__main__":
    data = {"Name": [], "Description": [], "Default Value": []}
    for entry in SETTINGS_MANAGER.settings:
        data["Name"].append(entry)
        data["Description"].append(SETTINGS_MANAGER.settings[entry]["description"])
        data["Default Value"].append(SETTINGS_MANAGER.settings[entry]["default"])

    print(tabulate(data, headers="keys"))
